# Generated by Django 5.1.3 on 2025-02-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
