# Generated by Django 5.1.3 on 2025-02-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
