# Generated by Django 5.0.2 on 2025-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='rh',
            new_name='rh_FK',
        ),
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='rol',
            new_name='rol_FK',
        ),
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='tipo_doc',
            new_name='tipo_doc_FK',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='is_active',
            field=models.IntegerField(),
        ),
    ]
