# Generated by Django 5.1.3 on 2025-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_usuariopersonalizado_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rh',
            name='nombre_tipo',
            field=models.CharField(max_length=3),
        ),
    ]
