# Generated by Django 5.1.3 on 2025-02-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ficha_estado'),
        ('mainapp', '0002_rename_rh_usuariopersonalizado_rh_fk_and_more'),
    ]

    operations = [
    ]
