# Generated by Django 5.1.3 on 2025-02-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_carnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carnet',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
