# Generated by Django 5.1.3 on 2025-02-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_merge_20250225_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios_fotos/'),
        ),
    ]
