# Generated by Django 5.1.3 on 2025-03-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_fichaxaprendiz_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichaxaprendiz',
            old_name='estado',
            new_name='estadoC',
        ),
    ]
